### ISSUE TITLE
Fishing rod repairing ?

### ISSUE THREAD

**Issue by RRadziejewski** [PyMan142/NewWorld-Auto-Fisher#2]
Hello anybody experienced issue that your fishing rod breaks and it's done ? Can we please have a support for this ?

Thanks!!

**Comment by Razikus** [comment]
yeah it definitely needs a bait and repair support

**Comment by PyMan142** [comment]
It does not currently have repair OR bait support

I have heard your request and im making it soon as I get out of que.

I will add repair easily, and see what I can do about bait. I may have to use all bait in the inventory (so keep what you want in the bank) is that okay?

**Comment by PyMan142** [comment]
> 
> 
> Hello anybody experienced issue that your fishing rod breaks and it's done ? Can we please have a support for this ?
> 
> Thanks!!

It does not currently have repair OR bait support

I have heard your request and im making it soon as I get out of que.

I will add repair easily, and see what I can do about bait. I may have to use all bait in the inventory (so keep what you want in the bank) is that okay?

**Comment by RRadziejewski** [comment]
Hello i don't know what am i doing wrong but it seems that it does not work, how i can create those png files by myself ? What should be my video options to make it work.

Regards

Rafał Radziejewski

**Comment by PyMan142** [comment]
> 
> 
> Hello i don't know what am i doing wrong but it seems that it does not work, how i can create those png files by myself ? What should be my video options to make it work.
> 
> Regards
> 
> Rafał Radziejewski

High graphics is what I use, they should be in the same folder with the script. 

Also im working on an updated version atm but it will still use pictures.

**Comment by RRadziejewski** [comment]
I really Like the solution and i will for sure test new version

niedz., 3 paź 2021, 19:05 użytkownik PyMan142 ***@***.***>
napisał:

**Comment by RRadziejewski** [comment]
Please include all the images in the repository :)

**Comment by PyMan142** [comment]
v2 Released
