### ISSUE TITLE
Bait support

### ISSUE THREAD

**Issue by RRadziejewski** [PyMan142/NewWorld-Auto-Fisher#3]
Hello almost in home but could we have support for bait ? It drastically improves fishing.

**Comment by PyMan142** [comment]
Yep that's coming next, but it's going to use all bait you have available, is that okay?

**Comment by RRadziejewski** [comment]
Of course this would be Perfect solution. Do you have any recomendations
how to take PNG files by myself ? What software ?

And of course i really appreciate this work thank you very much :)



niedz., 3 paź 2021, 23:36 użytkownik PyMan142 ***@***.***>
napisał:

**Comment by PyMan142** [comment]
You shouldnt need to take photos yourself, are you sure the problem wasn't that you didnt change the hotkey to "-"?

**Comment by PyMan142** [comment]
I used windows screen snip + paint

**Comment by RRadziejewski** [comment]
I have propably done something wrong will test IT out tomorrow evening more
carefully

Regards
Rafał

niedz., 3 paź 2021, 23:48 użytkownik PyMan142 ***@***.***>
napisał:

**Comment by PyMan142** [comment]
Yes please let me know, thank you.

**Comment by RRadziejewski** [comment]
In the logs it's just waiting to cast i have changed from LBM to - and it throws a pole but it's all it does not do anything more just throw it and throw it my settings are 1920/1080 HIGH windowed

**Comment by PyMan142** [comment]
Would you care to jump in a discord so I can see?

**Comment by RRadziejewski** [comment]
Sure we can do it

**Comment by PyMan142** [comment]
Fables#7687

**Comment by PyMan142** [comment]
.
