### ISSUE TITLE
I still encounter the bug when using the newlest run.py

### ISSUE THREAD

**Issue by EchoSixHIYA** [PyMan142/NewWorld-Auto-Fisher#7]
I left 1 bread bait to reproduce the bug,and the video is here.

https://user-images.githubusercontent.com/64828020/136638301-01ee857f-70d5-428d-8f20-142e2b4a6d81.mp4

the console info:

Press f1 to start ...
[Resumed]
holding the rod
putting on bait
casting
pressed - 
rod casted
Gotta click this fish
TIME TO FIGHT THE FISH
release
Hold1
Hold1
Hold1
Hold1
Hold1
Hold1
Hold1
release
release
Hold1
Hold1
Hold1
Hold1
Hold1
Hold1
Hold1
Hold1
release
release
Hold1
Hold1
Hold1
Hold1
Hold1
Hold1
Hold1
release
Hold1
Hold1
Hold1
Hold1
Hold1
release
release
release
release
release
release
release
release
release
release
release
Grats on the fish! (I hope) -- Restarting loop
holding the rod
putting on bait
You dont have any bait left
casting
pressed - 
rod casted
casting pole
casting pole
rod casted
casting pole
casting pole
rod casted
casting pole
rod casted
casting pole
[Exit]

I set the waterType to 1,and my Python version is 3.7

**Comment by PyMan142** [comment]
Ok try this

line 75 change confidence to 0.6
so

if pyautogui.locateOnScreen('polecasted.png', confidence = 0.6) == None:

**Comment by PyMan142** [comment]
And line 192 

same thing, confidence = 0.6

if status == 'waitingforbite' and pyautogui.locateOnScreen('polecasted.png', confidence = 0.6) != None :

**Comment by PyMan142** [comment]
Thank you! 

Also does this happen without bait too? Or only after you've run out of bait

**Comment by PyMan142** [comment]
So if waterType is 0 this will still happen everytime you cast?

**Comment by PyMan142** [comment]
Ok I changed run.py so that you don't have set set waterType anymore

**Comment by EchoSixHIYA** [comment]
YEP，it running courrently on my Pc,but i dont know weather it can work on the other computer

**Comment by PyMan142** [comment]
Ok I will give it a try and see if it throws me any problems

**Comment by PyMan142** [comment]
Pushed the update through, haven't had an issue yet. Thank you for this!
